# xenial (the default) or newer required
language: node_js
node_js:
  - 10 # Node 10 LTS or later required
addons:
  chrome: stable # make sure to have Chrome available
before_install:
  - npm install -g @lhci/cli@latest # install LHCI
script:
  - npm run build # build your site
  - npm test # run your normal tests
  - lhci autorun # run lighthouse CI against your static site
