name = "danestves-com"
type = "javascript"
account_id = "4f24d74527ce9e478456c5a88e466269"
zone_id = ""
route = "danestves.com/*"

kv_namespaces = [
  { binding = "CONTENT", id = "760848efe5c4465290589b70a68d3a33" },
  { binding = "VIEWS", id = "6c5859e1b34b48db9cf1f86bec228caf" }
]