name = "danestves-com"
type = "javascript"
workers_dev = true
account_id = "4f24d74527ce9e478456c5a88e466269"
zone_id = "fb4b53a2355b1f7287627892124bd7c5"
route = "dev.danestves.com/*"

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build"
watch_dir = "./build/index.js"

[build.upload]
format = "modules"
dir = "./dist"
main = "./worker.mjs"
