name: 🚀 Deploy

on:
  push:
    branches: [main, "feat/cloudflare-pages"]
jobs:
  changes:
    name: 🔎 Determine deployable changes
    runs-on: ubuntu-latest
    outputs:
      DEPLOYABLE: ${{steps.deploy_changes.outputs.DEPLOYABLE}}
      CONTENT: ${{steps.content_changes.outputs.CONTENT}}
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: '50'

      - name: ⎔ Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: 🔎 Determine content changes
        id: content_changes
        run: >-
          echo ::set-output name=CONTENT::$(node ./other/get-changed-content.js ${{
          github.sha }})

      - name: ❓ Content
        run: >-
          echo "CONTENT: ${{steps.content_changes.outputs.CONTENT}}"
        
  compile:
    name: 🛠 Compile MDX
    if: needs.changes.outputs.CONTENT != ''
    needs: [changes]
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: '50'

      - name: ⎔ Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: 🥶 Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-
            ${{ runner.OS }}-

      - name: 📦 Install npm packages
        run: cd ./other/mdx && npm install

      - name: 🚀 Compile and post MDX
        run: cd ./other/mdx && node ./compile-mdx.mjs --root ../../ --json --file ${{needs.changes.outputs.CONTENT}}
        env:
          DOMAIN: ${{ secrets.DOMAIN }}
          POST_CONTENT_BEARER_TOKEN: ${{ secrets.POST_CONTENT_BEARER_TOKEN }}

      - name: 🚀 Update content sha
        run: cd ./other/mdx && node ./update-content-sha.js
        env:
          COMMIT_SHA: ${{ github.sha }}
          DOMAIN: ${{ secrets.DOMAIN }}
          POST_CONTENT_BEARER_TOKEN: ${{ secrets.POST_CONTENT_BEARER_TOKEN }}