name: 🚀 Deploy

on:
  push:
    branches:
      - main
      - "feat/remix-cf-pages"
jobs:
  changes:
    name: 🔎 Determine deployable changes
    runs-on: ubuntu-latest
    outputs:
      DEPLOYABLE: ${{steps.deploy_changes.outputs.DEPLOYABLE}}
      CONTENT: ${{steps.content_changes.outputs.CONTENT}}
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: '50'

      - name: ⎔ Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: 🔎 Determine deployable changes
        id: deploy_changes
        run: >-
          echo ::set-output name=DEPLOYABLE::$(node ./other/is-deployable.js ${{
          github.sha }})

      - name: ❓ Deployable
        run: >-
          echo "DEPLOYABLE: ${{steps.deploy_changes.outputs.DEPLOYABLE}}"

      - name: 🔎 Determine content changes
        id: content_changes
        run: >-
          echo ::set-output name=CONTENT::$(node ./other/get-changed-content.js ${{
          github.sha }})

      - name: ❓ Content
        run: >-
          echo "CONTENT: ${{steps.content_changes.outputs.CONTENT}}"

  deploy:
    name: Deploy
    needs: [changes]
    if: needs.changes.outputs.DEPLOYABLE == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: 🥶 Cache dependencies
        if: $${{ !env.ACT }}
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-
            ${{ runner.OS }}-

      - name: ⎔ Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: 📦 Install npm packages
        run: npm install && npm run postinstall

      - name: 🛠 Build Remix app
        run: npm run build
        env:
          COMMIT_SHA: ${{ github.sha }}

      - name: 🎉 Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
        env:
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}

  compile:
    name: 🛠 Compile MDX
    if: needs.changes.outputs.CONTENT != ''
    needs: [changes]
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: '50'

      - name: ⎔ Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: 🥶 Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-
            ${{ runner.OS }}-

      - name: 📦 Install npm packages
        run: cd ./other/mdx && npm install

      - name: 🚀 Compile and post MDX
        run: cd ./other/mdx && node ./compile-mdx.mjs --root ../../ --json --file ${{needs.changes.outputs.CONTENT}}
        env:
          DOMAIN: ${{ secrets.DOMAIN }}
          POST_CONTENT_BEARER_TOKEN: ${{ secrets.POST_CONTENT_BEARER_TOKEN }}

      - name: 🚀 Update content sha
        run: cd ./other/mdx && node ./update-content-sha.js
        env:
          COMMIT_SHA: ${{ github.sha }}
          DOMAIN: ${{ secrets.DOMAIN }}
          POST_CONTENT_BEARER_TOKEN: ${{ secrets.POST_CONTENT_BEARER_TOKEN }}